"""适配器协议。真实模块通过这里接入，Mock 也实现同一组方法。"""

from __future__ import annotations

from typing import Any, List, Mapping, Optional, Protocol, Sequence

from .models import ESDFSnapshot, GraspCandidate, PlanningContext, VerificationResult, VerificationEvidence


class NavigationPort(Protocol):
    def navigate_to(self, station: str, *, task_id: str, generation_id: int) -> bool: ...
    def stop(self) -> None: ...
    def health(self) -> bool: ...


class PerceptionPort(Protocol):
    def observe(self, target_id: str, *, task_id: str, generation_id: int) -> Mapping[str, Any]: ...


class GraspNetPort(Protocol):
    def generate(self, target_id: str, arm: str, *, task_id: str, generation_id: int) -> List[GraspCandidate]: ...


class NvbloxPort(Protocol):
    def build_snapshot(self, *, task_id: str, generation_id: int) -> ESDFSnapshot: ...


class CuroboPort(Protocol):
    def plan(self, context: PlanningContext) -> Optional[Mapping[str, Any]]: ...


class DriverPort(Protocol):
    def move_to_camera_pose(self, arm: str) -> bool: ...
    def execute(self, trajectory: Mapping[str, Any], arm: str) -> bool: ...
    def open_gripper(self, arm: str) -> bool: ...
    def close_gripper(self, arm: str) -> bool: ...
    def stop_motion(self) -> None: ...
    def emergency_stop(self) -> None: ...
    def stationary(self) -> bool: ...


class VisualVerifierPort(Protocol):
    def verify(self, *, current_order: str, current_task: str, current_state: str, expected_visual_state: str, target_object: str = "", target_box: str = "", head_camera_image: Any = None, task_id: str = "", generation_id: int = 0) -> VerificationResult: ...

class EvidenceVerifierPort(Protocol):
    def verify_evidence(self, *, expected_state: str, evidence: Sequence[VerificationEvidence], policy: str = "all", task_id: str = "", generation_id: int = 0) -> VerificationResult: ...
