/**:
  ros__parameters:
    model_root: /home/lh/robot/models/grounded_sam2
    grounding_dino_model: grounding-dino-tiny
    sam2_model: sam2.1-hiera-tiny
    device: cuda
    use_fp16: true
    box_threshold: 0.30
    text_threshold: 0.25
    max_detections_per_camera: 10
    min_depth_m: 0.15
    max_depth_m: 1.50
    depth_scale: 0.001
    prompt_topic: /grounded_sam2/prompt
    left_image_topic: /left_camera/left_camera/color/image_raw
    left_depth_topic: /left_camera/left_camera/aligned_depth_to_color/image_raw
    left_camera_info_topic: /left_camera/left_camera/aligned_depth_to_color/camera_info
    left_arm_state_topic: /left/rm_driver/get_current_arm_state_result
    left_arm_state_request_topic: /left/rm_driver/get_current_arm_state_cmd
    left_tcp_pose_topic: /left/rm_driver/udp_arm_position
    right_image_topic: /right_camera/right_camera/color/image_raw
    right_depth_topic: /right_camera/right_camera/aligned_depth_to_color/image_raw
    right_camera_info_topic: /right_camera/right_camera/aligned_depth_to_color/camera_info
    right_arm_state_topic: /right/rm_driver/get_current_arm_state_result
    right_arm_state_request_topic: /right/rm_driver/get_current_arm_state_cmd
    right_tcp_pose_topic: /right/rm_driver/udp_arm_position
    left_camera_frame: left_camera
    left_base_frame: left_base
    right_camera_frame: right_camera
    right_base_frame: right_base
    left_T_tcp_camera: [-0.02554522396412673, -0.9996398979648244, 0.00821680774376263, 0.08586910992241736,
                        0.9996725402602394, -0.02555667584872534, -0.0012917310877542862, -0.044464920376784366,
                        0.0015012602247793257, 0.008181119510099087, 0.9999654071523172, 0.01167547161011385,
                        0.0, 0.0, 0.0, 1.0]
    right_T_tcp_camera: [0.023371282388568115, 0.9997033126848156, 0.006860740959957698, -0.08473545954929662,
                         -0.9997245307512411, 0.02335588196192684, 0.0023163315806366686, 0.04405154801645719,
                         0.0021554056984068033, -0.0069129866762761465, 0.9999737820770547, 0.011625538459209396,
                         0.0, 0.0, 0.0, 1.0]
    graspnet_checkpoint: /home/lh/Supermarket/graspnet-baseline/checkpoint-rs.tar
    graspnet_num_point: 20000
    graspnet_num_view: 300
    graspnet_collision_thresh: 0.01
    graspnet_voxel_size: 0.01
    graspnet_top_k: 20
    graspnet_select_best: 2
    grasp_model_tcp: [0.0, 0.0, 1.0, 0.0,
                      0.0, 1.0, 0.0, 0.0,
                      -1.0, 0.0, 0.0, 0.0,
                      0.0, 0.0, 0.0, 1.0]
